version: "3.7"

services:
  fastapi-post-app:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - ./:/user/src/app 
    command: python startapp.py --host 0.0.0.0 --port 8000 --reload true
    environment:
      - DATABASE_HOSTNAME=fastapi-post-app-postgres
      - DATABASE_PORT=5433
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=80bd9f478116aa5f9fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8bf9b1ac27e7a9a42d257
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_MINUTES=1445
      - REDIS_HOST=fastapi-post-app-redis
      - REDIS_PORT=6379
    depends_on:
      - fastapi-post-app-redis
      - fastapi-post-app-postgres
  
  fastapi-post-app-postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi
    ports:
      - "5433:5432"
    volumes:
      - fastapi-post-app-postgres-db:/var/lib/postgresql/data
  
  fastapi-post-app-redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  fastapi-post-app-postgres-db: